spring:
  profiles:
    active: ${ENV}
  validate:
    republic: ${COMMON_REPUBLIC}
    stars: ${STARS}

quasarfire:
  init:
    location: ${LOCATION_INIT}

firestore:
  collection: ${FIRESTORE_COLLECTION}

server:
  port: ${SERVER_PORT:8080}